import fs from "node:fs";
import path from "node:path";

const ROOT = process.cwd();
const UNRELEASED_DIR = path.join(ROOT, ".github/changelog/unreleased");
const ARCHIVE_DIR = path.join(ROOT, ".github/changelog/archive");
const DRAFT_EN_PATH = path.join(ROOT, ".github/changelog/DRAFT.md");
const DRAFT_ZH_PATH = path.join(ROOT, ".github/changelog/DRAFT.zh-CN.md");
const CHANGELOG_EN_PATH = path.join(ROOT, "CHANGELOG.md");
const CHANGELOG_ZH_PATH = path.join(ROOT, "CHANGELOG.zh-CN.md");

const CATEGORY_ORDER = ["Added", "Changed", "Fixed", "Removed", "Security"];
const ZH_CATEGORY = {
  Added: "新增",
  Changed: "变更",
  Fixed: "修复",
  Removed: "移除",
  Security: "安全"
};

const PUBLIC_EN_HEADER = `# Changelog

This file records published OpenCashier releases only.

It follows a lightweight Keep a Changelog structure and focuses on externally visible changes instead of mirroring commit history.

History that predates changelog adoption is backfilled at the public tag level. Work before the first public tag is summarized through that first tagged release instead of being reconstructed commit by commit.

Chinese version: [CHANGELOG.zh-CN.md](./CHANGELOG.zh-CN.md)`;

const PUBLIC_ZH_HEADER = `# 变更记录

这个文件只记录 OpenCashier 已发布的公开版本。

本变更记录采用轻量的 Keep a Changelog 结构，只记录外部用户可感知的变化，不复述 commit 历史。

在 changelog 机制建立之前的历史，会按公开 tag 的粒度补录。首个公开 tag 之前的内部开发，不按 commit 逐条回溯，而是汇总到首个公开版本中。

English version: [CHANGELOG.md](./CHANGELOG.md)`;

function fail(message) {
  console.error(message);
  process.exit(1);
}

function ensureDir(dir) {
  fs.mkdirSync(dir, { recursive: true });
}

function listFragmentFiles() {
  if (!fs.existsSync(UNRELEASED_DIR)) {
    return [];
  }

  return fs
    .readdirSync(UNRELEASED_DIR)
    .filter((file) => file.endsWith(".json"))
    .sort()
    .map((file) => path.join(UNRELEASED_DIR, file));
}

function loadFragments() {
  return listFragmentFiles().map((filePath) => {
    let data;

    try {
      data = JSON.parse(fs.readFileSync(filePath, "utf8"));
    } catch (error) {
      fail(`Failed to parse JSON fragment ${path.relative(ROOT, filePath)}: ${error.message}`);
    }

    if (!data || typeof data !== "object" || Array.isArray(data)) {
      fail(`Fragment ${path.relative(ROOT, filePath)} must contain a JSON object.`);
    }

    if (!Array.isArray(data.entries) || data.entries.length === 0) {
      fail(`Fragment ${path.relative(ROOT, filePath)} must contain a non-empty "entries" array.`);
    }

    data.entries.forEach((entry, index) => validateEntry(filePath, entry, index));

    return {
      filePath,
      data
    };
  });
}

function validateEntry(filePath, entry, index) {
  if (!entry || typeof entry !== "object" || Array.isArray(entry)) {
    fail(`Entry ${index} in ${path.relative(ROOT, filePath)} must be an object.`);
  }

  if (!CATEGORY_ORDER.includes(entry.category)) {
    fail(
      `Entry ${index} in ${path.relative(ROOT, filePath)} has invalid category "${entry.category}".`
    );
  }

  if (typeof entry.en !== "string" || entry.en.trim().length === 0) {
    fail(`Entry ${index} in ${path.relative(ROOT, filePath)} must include a non-empty "en" string.`);
  }

  if (typeof entry["zh-CN"] !== "string" || entry["zh-CN"].trim().length === 0) {
    fail(
      `Entry ${index} in ${path.relative(ROOT, filePath)} must include a non-empty "zh-CN" string.`
    );
  }
}

function groupEntries(fragments) {
  const grouped = {};

  for (const category of CATEGORY_ORDER) {
    grouped[category] = [];
  }

  for (const fragment of fragments) {
    for (const entry of fragment.data.entries) {
      grouped[entry.category].push(entry);
    }
  }

  return grouped;
}

function renderDraft(language, fragments) {
  const grouped = groupEntries(fragments);
  const header =
    language === "en"
      ? `# Internal Release Draft

This file is generated from \`.github/changelog/unreleased/*.json\`.

It tracks unpublished externally visible changes for upcoming releases and is not part of the public changelog.

Do not edit this file manually. Run \`pnpm changelog:draft\` or the sync workflow instead.`
      : `# 内部发布草稿

这个文件由 \`.github/changelog/unreleased/*.json\` 自动生成。

它用于汇总尚未发布、但对外部用户可感知的变更，不属于公开 changelog 的一部分。

请不要手工编辑这个文件。请运行 \`pnpm changelog:draft\` 或使用同步 workflow。`;

  const lines = [header];
  const hasEntries = CATEGORY_ORDER.some((category) => grouped[category].length > 0);

  if (!hasEntries) {
    lines.push(
      "",
      language === "en"
        ? "No unpublished externally visible changes are currently queued for release."
        : "当前没有待发布的对外可感知变更。"
    );
    return `${lines.join("\n")}\n`;
  }

  lines.push("", language === "en" ? "## Pending Release" : "## 待发布内容");

  for (const category of CATEGORY_ORDER) {
    const entries = grouped[category];
    if (entries.length === 0) {
      continue;
    }

    lines.push("", `### ${language === "en" ? category : ZH_CATEGORY[category]}`);
    for (const entry of entries) {
      lines.push(`- ${language === "en" ? entry.en : entry["zh-CN"]}`);
    }
  }

  return `${lines.join("\n")}\n`;
}

function parsePublicChangelog(content, language) {
  const normalized = content.replace(/\r\n/g, "\n").trim();
  const firstSectionIndex = normalized.search(/^## \[/m);
  if (firstSectionIndex === -1) {
    fail(`Could not find any released sections in ${language === "en" ? "CHANGELOG.md" : "CHANGELOG.zh-CN.md"}.`);
  }

  const referenceIndex = normalized.search(/^\[[^\]]+\]: /m);
  const header = normalized.slice(0, firstSectionIndex).trimEnd();
  const sectionsPart = normalized
    .slice(firstSectionIndex, referenceIndex === -1 ? normalized.length : referenceIndex)
    .trim();
  const referencesPart =
    referenceIndex === -1 ? "" : normalized.slice(referenceIndex).trim();
  const sectionBlocks = sectionsPart.split(/\n(?=## \[)/);
  const sections = sectionBlocks.map((raw) => {
    const match = raw.match(/^## \[([^\]]+)\] - ([0-9]{4}-[0-9]{2}-[0-9]{2})$/m);
    if (!match) {
      fail(`Failed to parse released section header in ${language === "en" ? "CHANGELOG.md" : "CHANGELOG.zh-CN.md"}.`);
    }
    return {
      version: match[1],
      date: match[2],
      raw: raw.trim()
    };
  });

  const references = {};
  if (referencesPart) {
    for (const line of referencesPart.split("\n")) {
      const match = line.match(/^\[([^\]]+)\]:\s+(.+)$/);
      if (!match) {
        fail(`Failed to parse reference link line "${line}".`);
      }
      references[match[1]] = match[2];
    }
  }

  return {
    header,
    sections,
    references
  };
}

function renderReleaseSection(version, date, fragments, language) {
  const grouped = groupEntries(fragments);
  const lines = [`## [${version}] - ${date}`];

  for (const category of CATEGORY_ORDER) {
    const entries = grouped[category];
    if (entries.length === 0) {
      continue;
    }

    lines.push("", `### ${language === "en" ? category : ZH_CATEGORY[category]}`);
    for (const entry of entries) {
      lines.push(`- ${language === "en" ? entry.en : entry["zh-CN"]}`);
    }
  }

  return lines.join("\n");
}

function renderPublicFile({ header, sections, references }, language) {
  const lines = [header, ""];

  for (const section of sections) {
    lines.push(section.raw, "");
  }

  const referenceLines = sections.map((section) => {
    const href = references[section.version];
    if (!href) {
      fail(`Missing reference link for version ${section.version}.`);
    }
    return `[${section.version}]: ${href}`;
  });

  lines.push(...referenceLines);
  return `${lines.join("\n").trim()}\n`;
}

function updateDraftFiles(fragments, mode) {
  const draftEn = renderDraft("en", fragments);
  const draftZh = renderDraft("zh-CN", fragments);

  if (mode === "write") {
    ensureDir(path.dirname(DRAFT_EN_PATH));
    fs.writeFileSync(DRAFT_EN_PATH, draftEn);
    fs.writeFileSync(DRAFT_ZH_PATH, draftZh);
    return;
  }

  if (!fs.existsSync(DRAFT_EN_PATH) || !fs.existsSync(DRAFT_ZH_PATH)) {
    fail("Internal draft files are missing. Run `pnpm changelog:draft` first.");
  }

  const currentEn = fs.readFileSync(DRAFT_EN_PATH, "utf8").replace(/\r\n/g, "\n");
  const currentZh = fs.readFileSync(DRAFT_ZH_PATH, "utf8").replace(/\r\n/g, "\n");

  if (currentEn !== draftEn || currentZh !== draftZh) {
    fail("Internal changelog draft files are out of date. Run `pnpm changelog:draft`.");
  }
}

function runValidate() {
  const fragments = loadFragments();
  updateDraftFiles(fragments, "check");
  console.log(`Validated ${fragments.length} changelog fragment(s).`);
}

function runDraft(mode) {
  const fragments = loadFragments();
  updateDraftFiles(fragments, mode);
  console.log(
    `${mode === "write" ? "Wrote" : "Checked"} internal changelog draft from ${fragments.length} fragment(s).`
  );
}

function runRelease(version, date) {
  if (!version) {
    fail("Usage: node scripts/changelog.mjs release <version> [date]");
  }

  const releaseDate =
    date || new Date().toISOString().slice(0, 10);
  const fragments = loadFragments();

  if (fragments.length === 0) {
    fail("No unreleased changelog fragments found.");
  }

  const enState = parsePublicChangelog(fs.readFileSync(CHANGELOG_EN_PATH, "utf8"), "en");
  const zhState = parsePublicChangelog(fs.readFileSync(CHANGELOG_ZH_PATH, "utf8"), "zh-CN");

  if (enState.sections.some((section) => section.version === version)) {
    fail(`Version ${version} already exists in CHANGELOG.md.`);
  }

  if (zhState.sections.some((section) => section.version === version)) {
    fail(`Version ${version} already exists in CHANGELOG.zh-CN.md.`);
  }

  const previousVersion = enState.sections[0]?.version;
  if (!previousVersion) {
    fail("Could not determine previous released version from CHANGELOG.md.");
  }

  enState.sections.unshift({
    version,
    date: releaseDate,
    raw: renderReleaseSection(version, releaseDate, fragments, "en")
  });
  zhState.sections.unshift({
    version,
    date: releaseDate,
    raw: renderReleaseSection(version, releaseDate, fragments, "zh-CN")
  });

  enState.header = PUBLIC_EN_HEADER;
  zhState.header = PUBLIC_ZH_HEADER;
  enState.references[version] = `https://github.com/aaaaaajie/OpenCashier/compare/${previousVersion}...${version}`;
  zhState.references[version] = `https://github.com/aaaaaajie/OpenCashier/compare/${previousVersion}...${version}`;

  fs.writeFileSync(CHANGELOG_EN_PATH, renderPublicFile(enState, "en"));
  fs.writeFileSync(CHANGELOG_ZH_PATH, renderPublicFile(zhState, "zh-CN"));

  const archiveTargetDir = path.join(ARCHIVE_DIR, version);
  ensureDir(archiveTargetDir);
  for (const fragment of fragments) {
    fs.renameSync(fragment.filePath, path.join(archiveTargetDir, path.basename(fragment.filePath)));
  }

  runDraft("write");
  console.log(`Released ${fragments.length} changelog fragment(s) into ${version}.`);
}

function main() {
  const [command, ...args] = process.argv.slice(2);

  switch (command) {
    case "validate":
      runValidate();
      return;
    case "draft":
      runDraft(args.includes("--check") ? "check" : "write");
      return;
    case "release":
      runRelease(args[0], args[1]);
      return;
    default:
      fail(
        "Usage: node scripts/changelog.mjs <validate|draft|release> [options]"
      );
  }
}

main();
